name: Swagserv-AntiAbuse
main: net.swagserv.andrew2060.antiabuse.AntiAbuse
load: POSTWORLD
version: 1.00
description: Protects against various commonly abused features on minecraft servers, from donator flying to faction ally/enemy swap.
commands:
  fly:
    description: Activate to fly
    usage: /<command>
permissions:
  antiabuse.fly:
    description: Gives access to fly 
  antiabuse.bypass.fly:
    description: Allows territorial bypass